services:
  brain-ai-vector-store:
    container_name: board-game-training-db
    image: "pgvector/pgvector:pg17"
    volumes:
      - ./postgres-dev-data/17/data:/var/lib/postgresql/data
    ports:
      - "5490:5432"
    expose:
      - "5490"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    restart: always
    environment:
      POSTGRES_DB: board-game-training-db
      POSTGRES_USER: ${BOARD_GAME_TRAINING_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${BOARD_GAME_TRAINING_DB_PASSWORD:-postgres}
