CREATE TABLE public.games (
    id bigint NOT NULL,
    age integer,
    artists character varying(255)[],
    authors character varying(255)[],
    bgg_id bigint,
    max_playtime integer,
    max_players integer,
    min_playtime integer,
    min_players integer,
    title character varying(255),
    type character varying(255),
    url_image character varying(255),
    url_thumbnail character varying(255),
    year integer
);

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1 INCREMENT BY 1
);

ALTER TABLE public.games ADD CONSTRAINT games_pkey PRIMARY KEY (id);
ALTER TABLE public.games ADD CONSTRAINT UKntmh3x14muumi2b0mskyio2j4 UNIQUE (bgg_id);

CREATE TABLE public.players (
    id bigint NOT NULL,
    name character varying(255),
    nickname character varying(255)
);

ALTER TABLE public.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_id_seq
    START WITH 1 INCREMENT BY 1
);

ALTER TABLE public.players ADD CONSTRAINT players_pkey PRIMARY KEY (id);
ALTER TABLE public.players ADD CONSTRAINT UKqgdybxl68dc8afxn41k2pasxg UNIQUE (nickname);

CREATE TABLE public.plays (
    id bigint NOT NULL,
    location character varying(255),
    id_game bigint,
    winner_id bigint
);

ALTER TABLE public.plays ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_id_seq
    START WITH 1 INCREMENT BY 1
);

ALTER TABLE public.plays ADD CONSTRAINT plays_pkey PRIMARY KEY (id);

CREATE TABLE public.play_players (
    play_id bigint NOT NULL,
    player_id bigint NOT NULL
);

-- Foreign keys
ALTER TABLE public.play_players
    ADD CONSTRAINT FK6klixhjpf6x2ix8v34ugh12eq FOREIGN KEY (player_id) REFERENCES public.players(id);

ALTER TABLE public.play_players
    ADD CONSTRAINT FKp2woirp1fvcu13vlxls3dw0kh FOREIGN KEY (play_id) REFERENCES public.plays(id);

ALTER TABLE public.plays
    ADD CONSTRAINT FKa72o52yygyuveym3t1sm4mee3 FOREIGN KEY (id_game) REFERENCES public.games(id);

ALTER TABLE public.plays
    ADD CONSTRAINT FKpyln8jt1mg97yoyfnk7psutco FOREIGN KEY (winner_id) REFERENCES public.players(id);
